---
# Copyright 2019 cabcookie.de
#
# Licensed under the GNU GENERAL PUBLIC LICENSE Version 3.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://raw.githubusercontent.com/cabcookie/wordpress-cloudformation-template/master/LICENSE
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Template to create an IAM User'
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
    - Label:
        default: 'Settings for IAM'
      Parameters:
      - InitialPassword
      - PasswordResetNeeded
Parameters:
  InitialPassword: 
    Type: String
    Description: Initial password for creation of IAM User.
    Default: your_initial_password
  PasswordResetNeeded:
    Type: String
    Description: Is a password reset needed for this user after initial login? It is true if no initial password is provided.
    Default: false
    AllowedValues: [ true, false ]
    ConstraintDescription: must only contain true or false
Conditions:
  HasNoInitialPassword: !Equals [!Ref InitialPassword, your_initial_password]
  UserWantsPasswordReset: !Equals [!Ref PasswordResetNeeded, true]
  IsPasswordResetNeeded: !Or [!Equals [!Ref InitialPassword, your_initial_password], Condition: UserWantsPasswordReset]
Resources:
  IAMUser:
    Type: AWS::IAM::User
    Properties:
      Path: /
      # Groups:
      #   - groupname
      LoginProfile:
        Password: !Ref InitialPassword
        PasswordResetRequired: true
      # Policies:
      #   - policyname
      # ManagedPolicyArns:
      #   - managedpolicyarn
Outputs:
  TemplateID:
    Description: IAM User
    Value: iamuser
  TemplateVersion:
    Description: IAM User Template Version
    Value: '1.0.0'
  StackName:
    Description: Stack name
    Value: !Ref AWS::StackName
  IamUserName:
    Description: Name of the created IAM User
    Value: !Ref IAMUser
  IamUserInitialPwd:
    Description: Initial password of the user if not specified by creation
    Condition: IsPasswordResetNeeded
    Value: !Ref InitialPassword
