---
# Copyright 2019 cabcookie.de
#
# Licensed under the GNU GENERAL PUBLIC LICENSE Version 3.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://raw.githubusercontent.com/cabcookie/wordpress-cloudformation-template/master/LICENSE
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Template to create a VPC'
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
    - Label:
        default: 'Settings for networking'
      Parameters:
      - IPNetwork
Parameters:
  IPNetwork:
    Description: 'Class B of VPC (XXX.XXX.0.0/16)'
    Type: String
    Default: '10.0'
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Sub ${IPNetwork}.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: VPC
#  VPCInternetGateway:
#    Type: AWS::EC2::InternetGateway
#    Properties:
#      Tags:
#        - Key: Name
#          Value: !Sub ${IPNetwork}.0.0/16
#  AttachGateway:
#    Type: AWS::EC2::VPCGatewayAttachment
#    Properties:
#      VpcId: !Ref VPC
#      InternetGatewayId: !Ref VPCInternetGateway
Outputs:
  TemplateID:
    Description: 'VPC'
    Value: 'vpc'
  TemplateVersion:
    Description: 'VPC Template Version'
    Value: '0.5.0'
  StackName:
    Description: 'Stack name'
    Value: !Sub '${AWS::StackName}'
  VPCId:
    Description: 'IP of the created VPC'
    Value: !Ref VPC
  VPCClassBNetwork:
    Description: 'Class B network of the VPC'
    Value: !Ref IPNetwork
