---
# Copyright 2019 cabcookie.de
#
# Licensed under the GNU GENERAL PUBLIC LICENSE Version 3.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://raw.githubusercontent.com/cabcookie/wordpress-cloudformation-template/master/LICENSE
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Template to create a VPC with private and public subnets'
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
    - Label:
        default: 'Settings for networking'
      Parameters:
      - ClassBIP
Parameters:
  ClassBIP:
    Description: 'Class B of VPC (10.XXX.0.0/16)'
    Type: Number
    Default: 0
    ConstraintDescription: 'Must be in the range [0-255]'
    MinValue: 0
    MaxValue: 255
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Sub 10.${ClassBIP}.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: VPC
#  VPCInternetGateway:
#    Type: AWS::EC2::InternetGateway
#    Properties:
#      Tags:
#        - Key: Name
#          Value: !Sub 10.${ClassBIP}.0.0/16
#  AttachGateway:
#    Type: AWS::EC2::VPCGatewayAttachment
#    Properties:
#      VpcId: !Ref VPC
#      InternetGatewayId: !Ref VPCInternetGateway
  SubnetPublicA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [0, !GetAZs '']
      VpcId: !Ref VPC
      MapPublicIpOnLaunch: true
      CidrBlock: !Sub 10.${ClassBIP}.0.0/19
      Tags:
        - Key: Type
          Value: Public
        - Key: AZ
          Value: A
  SubnetPublicB:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [1, !GetAZs '']
      VpcId: !Ref VPC
      MapPublicIpOnLaunch: true
      CidrBlock: !Sub 10.${ClassBIP}.32.0/19
      Tags:
        - Key: Type
          Value: Public
        - Key: AZ
          Value: B
  SubnetPublicC:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [2, !GetAZs '']
      VpcId: !Ref VPC
      MapPublicIpOnLaunch: true
      CidrBlock: !Sub 10.${ClassBIP}.64.0/19
      Tags:
        - Key: Type
          Value: Public
        - Key: AZ
          Value: C
  SubnetPrivateA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [0, !GetAZs '']
      VpcId: !Ref VPC
      CidrBlock: !Sub 10.${ClassBIP}.96.0/19
      Tags:
        - Key: Type
          Value: Private
        - Key: AZ
          Value: A
  SubnetPrivateB:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [1, !GetAZs '']
      VpcId: !Ref VPC
      CidrBlock: !Sub 10.${ClassBIP}.128.0/19
      Tags:
        - Key: Type
          Value: Private
        - Key: AZ
          Value: B
  SubnetPrivateC:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [2, !GetAZs '']
      VpcId: !Ref VPC
      CidrBlock: !Sub 10.${ClassBIP}.160.0/19
      Tags:
        - Key: Type
          Value: Private
        - Key: AZ
          Value: C
Outputs:
  TemplateID:
    Description: 'VPC with private and public subnets'
    Value: 'vpc'
  TemplateVersion:
    Description: 'Master Template Version'
    Value: '0.0.1'
  StackName:
    Description: 'Stack name'
    Value: !Sub '${AWS::StackName}'
  VPCId:
    Description: 'ID of the created VPC'
    Value: !Ref VPC
